cask_args appdir: "/Applications"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
brew "antigen"
brew "nvm"
brew "z"
brew "zsh"
brew "zsh-syntax-highlighting"
cask "font-fira-code"
cask "font-fira-mono-for-powerline"
cask "font-source-code-pro-for-powerline"
cask "visual-studio-code"
